### ISSUE TITLE
System.Windows.Interactivity.WPF 참조 이슈에 대해..

### ISSUE THREAD

**Issue by jamesnet214** [jamesnet214/leagueoflegends#1]
**Lol.GameRoom** 프로젝트에 참조된 `System.Windows.Interactivity.WPF` DLL은 .NET Framework를 사용하므로 기능이 정상적으로 동작하지 않을 수 있습니다.

이에 대한 해결 방안을 고민중입니다.

**Comment by Chenilove** [comment]
可能你的.net版本不兼容，这个项目应该是.net7.0

**Comment by jamesnet214** [comment]
DLL을 폐기하여 이슈를 닫습니다.
